services:
  clash-config-editor:
    build: .
    container_name: clash-config-editor
    ports:
      - '3100:3000'
    volumes:
      - ./configs:/app/configs
      - /root/.ssh:/root/.ssh:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ROUTER_HOST=192.168.32.1
      - ROUTER_USER=root
      - ROUTER_PORT=22
      - SUBCONVERTER_PORT=36611
    restart: unless-stopped
